name: opensim-viewer-bend
channels:
  - opensim-org
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2023.01.10
  - django=4.2.1
  - django-extensions=3.2.1
  - djangorestframework=3.14.0
  - docutils=0.20.1
  - freeglut=3.0.0
  - gettext=0.21.1
  - intel-openmp=2023.1.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - numpy=1.20.3
  - numpy-base=1.20.3
  - opensim=4.4
  - openssl=1.1.1t
  - pip=23.0.1
  - pydot=1.4.2
  - pyparsing=3.0.9
  - python=3.9.16
  - setuptools=66.0.0
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tzdata=2023c
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.38.4
  - pip:
      - certifi==2023.5.7
      - charset-normalizer==3.1.0
      - dataclasses-json==0.5.7
      - deprecated==1.2.13
      - docopt==0.6.2
      - idna==3.4
      - marshmallow==3.19.0
      - marshmallow-enum==1.5.1
      - mypy-extensions==1.0.0
      - packaging==23.1
      - pipreqs==0.4.13
      - pygltflib==1.15.6
      - requests==2.30.0
      - typing-extensions==4.5.0
      - typing-inspect==0.8.0
      - urllib3==2.0.2
      - wrapt==1.15.0
      - yarg==0.1.9
prefix: D:\anaconda3\envs\opensim-viewer-bend
